<?php

namespace BereczkyBalazs\WaaviTranslateAdmin\Transformers;

use BereczkyBalazs\WaaviTranslateAdmin\Abstracts\RequestDataTransformer;
use BereczkyBalazs\WaaviTranslateAdmin\Interfaces\RequestDataTransformerInterface;

class TranslateRequestDataTransformer extends RequestDataTransformer implements RequestDataTransformerInterface
{

}